### Suche alle Autos
GET {{restUrl}}

### Suche mit vorhandener Auto-ID
GET {{restUrl}}/00000000-0000-0000-0000-000000000001

### Suche mit vorhandener Auto-ID und Versionsnummer
GET {{restUrl}}/00000000-0000-0000-0000-000000000001
If-None-Match: "0"

### Suche mit vorhandener Auto-ID und falscher Versionsnummer
GET {{restUrl}}/00000000-0000-0000-0000-000000000001
If-None-Match: 0

### Suche mit ungueltiger Auto-ID
GET {{restUrl}}/YYYYYYYY-YYYY-YYYY-YYYY-YYYYYYYYYYYY

### Suche mit nicht-vorhandener Auto-ID
GET {{restUrl}}/99999999-9999-9999-9999-999999999999

### Suche mit vorhandenem Modell
GET {{restUrl}}?modell=a

### Suche mit nicht-vorhandenem Modell
GET {{restUrl}}?modell=xxx

### Suche mit vorhandener MODELLNUMMER
GET {{restUrl}}?modellnummer=978-3-8972-2583-1

### Suche mit vorhandenen Kategorienn
GET {{restUrl}}?kombi=true&suv=true

### Suche mit vorhandenem Kategorie "KOMBI"
GET {{restUrl}}?kombi=true

### Suche mit vorhandenem Kategorie "SUV"
GET {{restUrl}}?suv=true

### Suche mit nicht-vorhandener Property
GET {{restUrl}}?property=true

### Suche mit gueltiger AutoArt
GET {{restUrl}}?art=ELEKTRO

### Suche mit gueltigem Ps
GET {{restUrl}}?ps=1
